### ISSUE TITLE
Subtract time to negative timer bug

### ISSUE THREAD

**Issue by samuelbailey123** [bitfocus/companion-module-renewedvision-propresenter#106]
If propresenter has a timer that is negative and we try to subtract time from the timer it glitches and goes to positive 30 seconds :(

**Comment by greyshirtguy** [comment]
Thank you so much for taking time to submit a bug - this means I can check it out and (hopefully) fix it before the final release in early FeB

**Comment by greyshirtguy** [comment]
issue found, fix implemented.
Wil be in a future beta build... (working on a few other fixes before submitting - might take a few days if that is okay)

**Comment by samuelbailey123** [comment]
Awesome! Thanks @greyshirtguy no rush at all

**Comment by greyshirtguy** [comment]
Latest builds should have fix for this!
I will close issue for now (feel free to comment/re-open if find it is still a problem for you)
