### ISSUE TITLE
Old version when installing module in companion

### ISSUE THREAD

**Issue by joswis** [bitfocus/companion-module-renewedvision-propresenter#108]
Hi! maybe I'm doing it wrong but when I'm installing a module through companion GUI I'm missing a lot a features like macros and looks from later releases. Am i missing something or is companion pulling an old version?

**Comment by greyshirtguy** [comment]
Many new features have been added to the ProPresenter module **after** the current production release 2.1.4

To get the latest features (for now) you will need to download beta release of 2.2
![image](https://user-images.githubusercontent.com/1886513/152957780-edfd3f24-b9fa-4642-ab93-6aac1b30d988.png)
