### ISSUE TITLE
Feature Request: Show Prop

### ISSUE THREAD

**Issue by Wilmshurst** [bitfocus/companion-module-renewedvision-propresenter#11]
Hi Guys, 

i love this module, it has helped our church a lot. 

would it be possible to have actions for: 
- Show prop 

and then be able to select which prop for display by index?

Thanks again for your hard work!

**Comment by greyshirtguy** [comment]
Currently the module uses WebSockets to remote control ProPresenter.  I'm afraid there is not control of the Props built into the remote-control websocket of ProPresenter 6.
The only way to achieve this would be through the MIDI module - but Companion doesn't yet support sending custom MIDI.
There are two requests not yet closed asking for general MIDI support:
https://github.com/bitfocus/companion/issues/113
https://github.com/bitfocus/companion/issues/365
If they get closed, and you had the MIDI module, then you could setup buttons to show specific Props. Until then, we are out of luck (unless a new version of ProPresenter gets announced with more control built into the remote-control websocket)

**Comment by greyshirtguy** [comment]
Closing this for now (as there is no support built into the Pro6 or Pro7 API to trigger Props.
I assure you - I am checking for this on *every* new release and if/when they add it to the remote app - I will add it to Companion module (feel free to log support request with RV to add triggering Props to the remote app!! ;)
