### ISSUE TITLE
Props clear -> Cannot use "Clear Props" to clear props trigger with "Props Trigger (Network Link)"

### ISSUE THREAD

**Issue by mhoskinson7** [bitfocus/companion-module-renewedvision-propresenter#115]
Hey! I'm running 2.2.0-rc2 and ProP 7.8.2

I want to be able to use a button to trigger props and clear props. I was previously doing this through macros, but I am now trying to trigger props through the "Prop Trigger (Network Link)". This works great to trigger and clear specific props.

If I need to clear all of the props for some reason (something else needs to be full screen) I used to use a button for the action "Clear Props" to clear any and all props (even if not triggered specifically from "Prop Trigger (Network Link)". The "Clear Props" action does not work if I trigger a prop using the "Prop Trigger (Network Link)" action.

[GRACE-300574_companion_log_20220228-1554.csv](https://github.com/bitfocus/companion-module-renewedvision-propresenter/files/8157176/GRACE-300574_companion_log_20220228-1554.csv)
You can see in the log that I trigger button 1.2 (the network link prop trigger). I have that set on a 10 second delay to clear that prop (via network link clear prop). If I wanted to clear the prop earlier, I had button 1.21 set to do the "Clear Props" action to clear all props, but it doesn't clear the prop triggered via network link prop trigger. I have to wait the full 10 seconds for my network link prop trigger to go into effect. 

A video example taken when I was clicking through with the log. It waited the 10 seconds instead of when I hit "Clear Props" action in companion.
https://user-images.githubusercontent.com/94998006/156065631-a13984be-f798-4255-91ca-eb7baeedc413.mp4

**Comment by greyshirtguy** [comment]
I can't replicate this in windows pro7.8.3 beta....For me, clear props just works....regardless of how props were triggered.

Can you show screenshots of the button configs?
What exact version of Pro7 are you running

**Comment by mhoskinson7** [comment]
Running Windows as well but I was on Pro 7.8.2. I just updated to the Pro 7.8.3 beta and it is now working correctly as you are experiencing. 

I'll close this out but the button configs are included below for clarity.
![Prop tigger](https://user-images.githubusercontent.com/94998006/156186276-dc80d0c4-7f9f-4f19-8b2f-5dd4d37156b9.png)
![prop clear](https://user-images.githubusercontent.com/94998006/156186287-b50509b0-4e17-4da1-a529-a0d44412c143.png)
