### ISSUE TITLE
Previous and next slide commands not scrolling preview window

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-renewedvision-propresenter#117]
The preview side of the screen scrolls as expected when using the arrows or space bar to advance slides but not when using a command from Companion.  The slides advance as expected but the preview window stays in the same position.  Any ideas or is this a bug that could maybe be patched with the remote protocol? Would be great to have this window move along with us.  Thanks!

**Comment by greyshirtguy** [comment]
This is how PRo7 behaves when remotely triggered (you will see the same when using the mobile remot app).
Sorry nothing can be done form "our end" - The only fix would to have RV update PRo7 to change it's behaviour (if you are going to log a ticket with them, I suggest pointing out that it does it with their own app in addition to Companion)
