### ISSUE TITLE
Request for command to adjust the slide/background transition times

### ISSUE THREAD

**Issue by IanPurpose** [bitfocus/companion-module-renewedvision-propresenter#126]
Request for a button to adjust the transition times for slides and the backgrounds in the media bins.

**Comment by greyshirtguy** [comment]
I would love that too!
Unfortunately, according to my memory, there no API or method to change those durations from outside the UI itself!
If they update the API (or another method springs to mind) - I'll re-visit this!
Sorry for the bad news!

**Comment by IanPurpose** [comment]
It is all good, I appreciate the response! Loving the program, keep up the
good work!!
