### ISSUE TITLE
7.9 (118030345) - Hardly any preset options available

### ISSUE THREAD

**Issue by BlueToast** [bitfocus/companion-module-renewedvision-propresenter#129]
What am I doing wrong?? We hardly have any preset options (in contrast to the screenshot of all the buttons from HELP.MD) displayed by this module when connected to our ProPresenter with Bitfocus Companion

This is all we have:
![image](https://user-images.githubusercontent.com/516539/170837229-8caaeae9-7f5d-43e4-b4fe-906136716ed0.png)
![image](https://user-images.githubusercontent.com/516539/170837235-55c03587-e5c7-4c41-93c9-fd04f0b2b05f.png)
![image](https://user-images.githubusercontent.com/516539/170837238-60ef6194-0773-4ded-8dd1-c7b782c7328c.png)

Here's our Connection configuration in Bitfocus Companion:
![image](https://user-images.githubusercontent.com/516539/170837253-e319c9df-e9b2-4d6e-bb6a-f70e607ba955.png)
![image](https://user-images.githubusercontent.com/516539/170837260-dc84db71-bdad-4346-8d36-0f7619735b10.png)
![image](https://user-images.githubusercontent.com/516539/170837264-24651859-418e-47b6-a155-4831ff633239.png)
![image](https://user-images.githubusercontent.com/516539/170837272-252ffddb-a402-46e8-8c8f-652e28c63c7f.png)
![image](https://user-images.githubusercontent.com/516539/170837279-e2f1b352-79db-4d69-907b-681f2bdf1fa1.png)

Here's the version of Bitfocus Companion we are running on:
![image](https://user-images.githubusercontent.com/516539/170837314-b60e107b-764d-49cc-8ff9-a730717c3a30.png)

Here's the version of ProPresenter we are running on:
![image](https://user-images.githubusercontent.com/516539/170837321-732e1328-ef6b-4e65-a335-c8afb1c8624c.png)

Here's our ProPresenter Network configuration:
![image](https://user-images.githubusercontent.com/516539/170837332-129189db-bdd9-4a26-9b58-b758adb0a900.png)

With all this, the options we have available in Bitfocus Companion looks nothing remotely like all the buttons and functions shown in this HELP.MD screenshot:
![image](https://user-images.githubusercontent.com/516539/170837385-748865fd-4d22-4237-b54c-94972600e290.png)

And, nowhere near the number of options and functions as shown in the Elgato Streamdeck software w/ Renewed Vision ProPresenter module.

I've read the HELP.MD multiple times. What am I missing? What's wrong? Why don't we have all the functions like next slide, etc?

**Comment by greyshirtguy** [comment]
That last screenshot is intended to be an example of the types of actions availble to use when setting up buttons - it's not a list of presets! These  buttons were created manually - without presets - which is what you will have to do.

I have thought about make some presets - but they really don't save much time (if any) over just adding an action to a button manually.  I'll revisit that thought and consider making some more presets....

**Comment by BlueToast** [comment]
> That last screenshot is intended to be an example of the types of actions availble to use when setting up buttons - it's not a list of presets! These buttons were created manually - without presets - which is what you will have to do.
> 
> I have thought about make some presets - but they really don't save much time (if any) over just adding an action to a button manually. I'll revisit that thought and consider making some more presets....

Would you be able to share an example export of Bitfocus Companion buttons you've created so that I can import and study them? I feel like this would help set me up for success in trying to understand how this works, and then customize it for our environment.
