### ISSUE TITLE
Pause/Resume Currently Playing Video

### ISSUE THREAD

**Issue by scpurples** [bitfocus/companion-module-renewedvision-propresenter#134]
Enhancement - I would like to see a hook in the Propresenter module where I can pause the video that is currently paying from a Media playlist. I would also like to see a hook where I can resume the video that is currently paused from a Media playlist.

We use Propresenter for, among other things, animated lower thirds. After one animates in, we would like to pause it. When it is time to let it animate out, we would like to resume it. 

I have tried everything I know with the current version to no avail, but if the current version DOES do this, please let me know how and accept my apology.

**Comment by tacvideo** [comment]
@scpurples I don't think that's going to happen. There's no ability for this in the PP7 API (see the **API Documentation** in the **Preferences / Network Tab**... I recently looked for this to be able to Play/Pause videos for classes, ended up playing the videos thru a Roku that I fed into PP7 using **Video Inputs**, Companion can then send Play/Pause etc. to the Roku.
Then wherever class slides indicate to play the video, you create a blank slide that Activates the Video Input...

**Comment by scpurples** [comment]
There may be a misunderstanding. I was looking for a way to pause a video in the media layer playlist, then resume it. Not a video input.

Turns out there are hooks to do that in the new Propresenter API and, while I can't find a way to access those from the current Companion module for Propresenter, I CAN access them from the generic HTTP Companion module using HTTP GETS:

select the media playlist: /media/playlist/<playlist name>/focus  
play an item from the selected media playlist: /media/playlist/focused/<playlist item number>/trigger
pause the current playing item: /transport/presentation/pause
resume the currently paused item: /transport/presentation/play

So the good news is I got it working. And if these actions ever get incorporated into the Companion module for Propresenter, I'll switch out of the HTTP Companion module and use those.

Thanks, you can close this out.

**Comment by scpurples** [comment]
select the media playlist: /media/playlist/(name of media playlist)/focus
play an item from the selected media playlist: /media/playlist/focused/(media playlist item number)/trigger
pause the current playing item: /transport/presentation/pause
resume the currently paused item: /transport/presentation/play

**Comment by greyshirtguy** [comment]
I do plan to make a new module that supports the new API.
It will enable a few functions/features that the old API used by the current module does not (not many - but a few).

Until then, I've been guiding people to use HTTP module to access the new API - well done!
