### ISSUE TITLE
"Clear Background" should read "Clear Media"

### ISSUE THREAD

**Issue by Brotuulaan** [bitfocus/companion-module-renewedvision-propresenter#137]
This is merely a labeling issue, but it doesn't match Pro7's naming system. I was confused when setting up clear buttons why the clear media was absent from the list, and then I realized there were a few that didn't seem to belong. I found that "Background" clears the media layer, so I have it set up. But fixing the label would be helpful to people setting up that function in future. I've never seen "telestrator" in Pro7, so I'm guessing that's a feature for Pro6.

**Comment by greyshirtguy** [comment]
This is a the original lanuge used in Pro6 - which the module still supports.
I've been umming and arrhing for months about updating this module to support the new Pro7 API or to make a new one...
I'll consider this food for thought to suggest a new module would be less confusing to use.
(And yes, Telestrator is a Pro6 only feature - at the time of writing this)
