### ISSUE TITLE
PP7 lags with Companion open 

### ISSUE THREAD

**Issue by digitalsky777** [bitfocus/companion-module-renewedvision-propresenter#139]
Been using Companion for months with NO issues. All of the sudden PP7 will lag to the point of being unresponsive with Companion open. I then upgraded to the latest version and it did not resolve the problem. Running PP7 on a Windows 10 machine. When I close Companion then PP7 returns to being stable.

**Comment by greyshirtguy** [comment]
Please see this section of the help/intructions:
![image](https://user-images.githubusercontent.com/1886513/182050720-3fff85ac-a3a0-4518-9f1d-2170b777b202.png)
Can you confirm if using these settings helps?

**Comment by digitalsky777** [comment]
Thank you, this is super helpful!  I have gone ahead and disabled it all
and everything is back up to normal.  Weird thing is...I do not remember
turning it on in the first place.
