### ISSUE TITLE
When will this updated module v2.5.4 be included in Companion? 

### ISSUE THREAD

**Issue by agbrint** [bitfocus/companion-module-renewedvision-propresenter#140]
Wondering when this updated module will be included in Companion, either a stable release or beta release?

Otherwise how do I test the new midi functionality?  This will be a huge leap in making my production more automated.

**Comment by greyshirtguy** [comment]
Midi got pulled out of Companion - from memory - there were some show-stopping isuses with some required binary libraries that broke the Companion build.  I don't think it's high on the list to get fixed.  I'll ask again!

**Comment by BenJamesAndo** [comment]
I see in v2.5.5 MIDI is added in. Does it also work on Windows, as I haven't been able to get it to work.

**Comment by greyshirtguy** [comment]
Oh wow - they managed to compile in those changes!  I'll download to test/learn if it works on Windows!

**Comment by greyshirtguy** [comment]
Oh wow - what a moment in the history of the Pro7 on Windows!  It works!
I'll make a "show and tell" video soon

**Comment by BenJamesAndo** [comment]
That is very significant! Can't wait to see the video. This would be a game changer for sure.

**Comment by greyshirtguy** [comment]
Are you in ProPresenter user group - just posted in there (awaiting admin approval).
in the meantime - I going to take a wild guess at your issue and ask: _Do you know that Windows has NO built-in software MIDI bus/ports like MacOS does - you have to install and use third party software to create a software MIDI bus/port: eg loopMIDI_ ?

**Comment by BenJamesAndo** [comment]
Ah yes that's right, you're an Aussie too. I remember seeing you in the ProPresenter 7.9 Release Event video.
No wonder we're the only two up for this historical moment :)

I've got very little experience working with MIDI, but that makes sense. I'll have a little play and see if I can get it, otherwise I'm happy to wait for the video, as I am in the Facebook user group.

**Comment by greyshirtguy** [comment]
https://www.facebook.com/groups/ProPresenterUsersGroup/posts/3200822383516962/

**Comment by JeffreyDavidsz** [comment]
This thread is about midi. This module had an midi listener build into it which pressed a button. This function is removed as the modules are sandboxed from the system now (Companion V3) and at this moment certain call are not allowed. I'll close this.
