### ISSUE TITLE
Variable for Time Remaining in Video

### ISSUE THREAD

**Issue by Hazzard13** [bitfocus/companion-module-renewedvision-propresenter#141]
**Is your feature request related to a problem? Please describe.**
We're in a place with a companion streamdeck, where I'm controlling a show and can see the ProPresenter output, but not ProPresenter itself. I'm trying to use feedback to see the time remaining on a video, as it's impossible to know otherwise.

**Describe the solution you'd like*
A variable outputting this value, as shown in the Pro7 sidebar, or the "Video Countdown" linked text, so I can conditionally bind it to a button's feedback.

**Describe alternatives you've considered**
A custom feedback type, although I believe this would be more work and less flexible, albeit more discoverable.

**Additional context**
This is something I thought I could do with the "video countdown timer", although that must be something different, as it doesn't react to me playing a video in testing.

**Comment by greyshirtguy** [comment]
There already is a variable for **video_countdown_timer**
![image](https://user-images.githubusercontent.com/1886513/187118869-d3a0ee8a-566b-49d6-b6a4-582cf5d006ea.png)
The module can only get that info from the Stage Display connection - so you have to enable that:
![image](https://user-images.githubusercontent.com/1886513/187118978-40fadaaf-2ab1-48da-b85b-59abc52c0883.png)
