### ISSUE TITLE
How do I even download this??!

### ISSUE THREAD

**Issue by soni801** [bitfocus/companion-module-renewedvision-propresenter#15]
There are no .streamDeckPlugin files here, and there is no link pointing me towards a download.

You say commands and shit which nobody needs, but don't even make it possible to download. What is the point of having a public project if the only think it contains is the HELP file and the resources for it??

(I'm done being toxic now, can you tell me where to donload, and how, thanks)

**Comment by SteveTherrien** [comment]
Hi @soni801,

This repo only contains the ProPresenter module's source code for the Companion software (https://bitfocus.io/companion/) and is only useful if you're a developer or are reporting a bug. It's one of many modules available for Companion (https://github.com/bitfocus).

The files here cannot be used directly with the Stream Deck software. Check out the [Companion website](https://bitfocus.io/companion/) or their [Getting Started](https://github.com/bitfocus/companion/blob/master/documentation/gettingstarted.md) document for more information.

**Comment by willosof** [comment]
Wow. That's a pretty shitty way to ask for help.
