### ISSUE TITLE
Stuck "Waiting for connection to start" in 3.0.0 beta

### ISSUE THREAD

**Issue by nsutclif** [bitfocus/companion-module-renewedvision-propresenter#158]
**Describe the bug/issue**
Tried updating to the 3.0.0 beta of Companion.  Other features and modules seem to work in my environment, but propresenter module just reports "Waiting for Connection to start"

**To Reproduce**
1. Try to add a Connection to propresenter.
2. Try to view module settings
I am running Companion 2.4.2 with Propresenter Connection successfully on Windows.  I tried exporting that configuration and importing it into a 3.0.0 install on a Raspberry Pi.  I also tried a fresh install of 3.0.0 on Windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/6785756/233840075-19424659-846a-4b48-a853-54abdfd81d36.png)

**Versions/Environment (please complete the following information):**
 - ProPresenter Version 7.10.4
 - OS of ProPresenter Machine: WIndows
 - Companion Version: [3.0.0 (3.0.0+5810-beta-54eaf478)](https://bitfocus.io/companion/)
 - OS of Companion machine: Ubuntu 64 bit ARM (Raspberry Pi).  Also tried Windows
 - Debug log output when issue occurs: Nothing in the log.  I haven't found the "debug log" feature...

**Comment by Julusian** [comment]
This is better now
