### ISSUE TITLE
"revert back to previous stage display"

### ISSUE THREAD

**Issue by officialmattsnyder** [bitfocus/companion-module-renewedvision-propresenter#16]
Feel free to just close this right away if this isn't the place for this kind of question. But, is there a way to make this module "undo" a stage display change?

Basically, I'm trying to create a button that swaps stage displays (to show a different clock), then goes back to whatever the previous display was on after a set amount of time. The idea being that I can tell a speaker to "talk for 2 minutes longer than you thought", give him a 2 minute timer, and then send him back to his old timer without having to have multiple timers on screen.

Since the module can "see" what display index is currently active in the config page, is there a way to hold onto that data and use it in the button press sequence?

**Comment by greyshirtguy** [comment]
Did you know Companion has a built in optional latch function for each button?
Maybe that will be enough for what you need?
How it works, is that you assign different desired actions to both Key Down and Key Up...Then you check the Latch (toggle) option (visible once you've set the button style).
This puts the button into a latch mode where all the DOWN actions are run the first time it is pressed and then all the UP actions are run the next time is pressed - and it keeps swapping back and forth....
