### ISSUE TITLE
Feature Request: Instance Feedback

### ISSUE THREAD

**Issue by cgarwood** [bitfocus/companion-module-renewedvision-propresenter#18]
Feedback support would be incredibly useful. I have buttons for different stage display layouts, and I would like to change the background of the button for the currently active stage display layout

**Comment by chrisrouse** [comment]
Are you creating buttons on your Streamdeck for each layout? If so, just add internal button color actions to each button to change colors on each button.

<img width="583" alt="Screen Shot 2019-06-03 at 7 06 36 PM" src="https://user-images.githubusercontent.com/2112469/58842233-dd40a980-8632-11e9-8496-ea3c45a973aa.png">
<img width="563" alt="Screen Shot 2019-06-03 at 7 06 50 PM" src="https://user-images.githubusercontent.com/2112469/58842234-dd40a980-8632-11e9-8683-30e4e7d3faf7.png">
![buttons](https://user-images.githubusercontent.com/2112469/58842258-f8abb480-8632-11e9-83c1-48a3c689ffa2.gif)

**Comment by cgarwood** [comment]
We use cues in ProPresenter slides to change the layout occasionally, which would cause the streamdeck to get out of sync using that method.

**Comment by willosof** [comment]
Do we have feedbacks that isn't based on real data from the application??

**Comment by cgarwood** [comment]
#19 adds support for stage display feedback. Are there any other feedbacks that would be useful to add? I can take a look at adding them.
