### ISSUE TITLE
Set Slide/Media Transition Times

### ISSUE THREAD

**Issue by jamseong** [bitfocus/companion-module-renewedvision-propresenter#181]
**Feature Request**
Trigger that allows you to set the transition times for slides/media items. You could specify a different transition time for each trigger (e.g. 0.5s, 2s, 5s, etc)

**Additional context**
It could be useful to set transition times faster for up-beat songs so the cuts are cleaner, and for slower songs there could be more crossfades between camera angles.

**Comment by greyshirtguy** [comment]
I wish there was a way to do this - but there is nothing in the old (or new) api for this.
