### ISSUE TITLE
Feature Request: Variable for key song is played in

### ISSUE THREAD

**Issue by commputethis** [bitfocus/companion-module-renewedvision-propresenter#182]
**Is your feature request related to a problem? Please describe.**
Yes and No.  We are getting to a point where we have lots of Macros in ProPresenter that we have to make sure get added to the first slide of a song.  Sometimes this causes some issues with timing and/or forgetting to add one.  This particular one is for changing sending a command to Companion to press a button which sends a command to SoundRack SoundGrid program to load a snapshot based on the key a song is played in.

**Describe the solution you'd like**
What we would like to be able to do is create a trigger in Companion that would "press" a specific button based on the key the song is played in.  This is defined in ProPresenter for the song.  We would like to see a variable created in this module that we could reference in the condition of the trigger.  It would also be used to change the look of the button for that key on the stream deck.

**Describe alternatives you've considered**
I am not sure what other alternative solutions we would have for this.

**Additional context**
![ProPresenter - Song Key](https://github.com/bitfocus/companion-module-renewedvision-propresenter/assets/17625274/6f30a1bb-fa53-4c03-80b5-a3c018941ba0)

**Comment by greyshirtguy** [comment]
Sorry - there is no API (either documented or undocumented) that we know about to get the selected key of MT documents...
