### ISSUE TITLE
Make 127.0.0.1 default, or explain the concept of localhost in documentation?

### ISSUE THREAD

**Issue by mathiasha** [bitfocus/companion-module-renewedvision-propresenter#20]
The documentation for how to set up this module is not very good.

I am an experienced developer, used to using Github, but I simply cannot figure out to get this module running.

Why is there no README file in this repo? (I guess the guide is in the help.md file, but that is not conventional)
Why is there no guide to setting up the connection between ProPresenter and Companion module?
The config interface does not give much help.

**Comment by mathiasha** [comment]
My main issue is that I don't see an IP address anywhere, even though that is what the module is asking for.

<img width="672" alt="Screenshot 2019-07-29 at 01 33 57" src="https://user-images.githubusercontent.com/8741691/62014412-144dba00-b1a1-11e9-9b96-7568044f5299.png">

**Comment by willosof** [comment]
Hi Mathias. I'm not sure what you know or don't know based on your questions, but it seems to me that you're trying to use this repository alone. This is a sub repository for the companion project.

Try downloading companion from http://bitfocus.io/companion/

**Comment by mathiasha** [comment]
Of course i am not trying to install this module alone. I added this module to companion. 

But i am confused as to why there is no real documentation on how to connect this module with ProPresenter running on my Mac.

**Comment by willosof** [comment]
And, for the record, HELP.md files is used inline in the companion application, and is not a README file. That's why it's not called README.md.

**Comment by willosof** [comment]
The IP you're after is the ip of the computer running ProPresenter, like everything else in companion.
127.0.0.1 if it's on the same computer as companion.

**Comment by willosof** [comment]
https://en.wikipedia.org/wiki/Localhost

**Comment by mathiasha** [comment]
That’s fine, but it is a bit weird when the convention for a github repo is to add that to the documentation the readme file. 

Thanks I will try that :)

**Comment by mathiasha** [comment]
I did try typing in localhost to the up field, but it seems that there is some validation that doesn’t allow anything other than an IP address. Maybe that is something that needs to be looked at?

**Comment by josephdadams** [comment]
@mathiasha if Companion is running on the same computer as ProPresenter, use IP Address 127.0.0.1. Put in the port that’s listed from the network tab of Pro6. (The above screenshot shows 60745. Enable the ProPresenter remote and set a password. Put that password in the config settings in Companion. You should be good to go.

**Comment by JeffreyDavidsz** [comment]
@mathiasha I don't think basic network knowledge is something that needs to be added to each module. Especially when I see that the correct answer to your question is already given including explanation. When you still try to type localhost where there should be an ip, than I would say just read a bit better. It might be a good idea to add a general FAQ where we explain what localhost is (like the new topic said)

**Comment by mathiasha** [comment]
> I don't think basic network knowledge is something that needs to be added to each module.

I disagree. If you want people to use the module, then having a good guide for setting it up essential.

> Especially when I see that the correct answer to your question is already given including explanation. When you still try to type localhost where there should be an ip, than I would say just read a bit better.

I am sorry but I actually don't know what explanation you are referring to. 

I think it makes sense to change the module to support localhost in the ip field, and then writing a short note to explain the user to use localhost if running companion and ProPresenter on the same computer.

**Comment by greyshirtguy** [comment]
I am happy to "put my hand up" for this if that helps.
I can do the following three items in my fork of this module and then submit a pull request...

1. Perhaps defaulting "ProPresenter IP" to 127.0.0.1 is not a bad idea?
2. I am happy to add a few lines at the top of Help.md to give simple some guidance for networking novices.
3. The module currently does restrict input for "ProPresenter IP" to IP address format: 'REGEX_IP' -  I wonder if we might remove that restriction and allow hostnames? *ANYONE* got any thoughts on this?

**Comment by josephdadams** [comment]
A default to 127 won’t hurt anyone who needs to change it.

I think removing the regex just for the benefit of hostname support would only help a small number of users and could lead to more support requests because of DNS issues or mistyped IP’s. 

If/when we are able to add MDNS support to Companion, I’m pretty sure ProPresenter announces itself via zeroconf/mdns/bonjour and we could encourage module configs based on that info, to help people who struggle with knowing or typing in an IP address correctly.

**Comment by greyshirtguy** [comment]
I had the same concern as you with the mistyped IP's but I was on the fence... For now, I'll drop idea #3.

ProPresenter certainly uses Bonjour to advertise its services!
The two web-socket based network services used by this modules are
_pro6porremote._tcp. and _pro6stagedsply._tcp.

Note that bonjour only works in a single broadcast domain (subnet). The very small # of users that have machines on different subnets will still need to manually configure.

**Comment by greyshirtguy** [comment]
First draft changes is done in my fork..
Updated help.md is here: https://github.com/greyshirtguy/companion-module-renewedvision-propresenter/blob/master/HELP.md

**Comment by cgarwood** [comment]
@greyshirtguy updated help looks good to me

**Comment by JeffreyDavidsz** [comment]
Funny thing is this module has one of the most expanded HELP.md files. Anyway I've changed the default IP to 127.0.0.1 (which is localhost) and updated the HELP.md file. Be aware; I saw some other changes that weren't in the core yet. So please test the 2.0 build first before we add it to 1.4. This because 1.4 will be released soon as stable
