### ISSUE TITLE
Exception if port number is not defined

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-renewedvision-propresenter#22]
Configuration should define port number as mandatory, and it should not try to connect when the port is undefined.

Worst case, it should report an error to the log with "port number is not specified" or something, when you try to use the module.

**Comment by greyshirtguy** [comment]
Will fix this soon!

**Comment by greyshirtguy** [comment]
Sorry - life been super busy... still not done..

**Comment by SteveTherrien** [comment]
No problem, I'm putting together a commit this.
