### ISSUE TITLE
Request: Hotkey for ‚Specific Slide‘

### ISSUE THREAD

**Issue by EnerGiehl** [bitfocus/companion-module-renewedvision-propresenter#23]
Hey. I‘d Love to get Hotkey Support for Specific Slide. Cause Keybindings will remain if you enter additional slides. So you dont have to edit all numbers again

**Comment by SteveTherrien** [comment]
I'd love to see that too, but hotkeys can't be triggered with the ProPresenter API.

I once experimented with scanning the current presentation and noting which slide numbers corresponded to which slide groups, so it would know that triggering "Chorus 1" meant triggering slide #.

It worked pretty well, until I realized there's no know way of knowing when someone edited the current presentation (like adding/removing/splitting slides, reordering them, changing arrangements, etc.), which meant my group/slide number mappings would then trigger the wrong slides.

Have you tried the [VICREO module](https://github.com/bitfocus/companion-module-vicreo-hotkey/blob/master/HELP.md) to trigger hotkeys instead? It should work just as well, except ProPresenter will need to be in the foreground to receive the hotkeys.

**Comment by greyshirtguy** [comment]
Hmmm..I have an idea to send keystrokes to processes (in background or foreground)

I have background strokes being sent to ProPresenter working on my Mac during Initial testing.
I'll need some time test and figure out details. I'll def need a listener hotkey sender - so I might end up doing a pull request on the VICREO module.

**Comment by JeffreyDavidsz** [comment]
@greyshirtguy what do you have in mind? VICREO-Listener is a keyboard emulator, so it will send keystrokes to the machine and normally only the active window should receive it? If you want some extra functionality let me know how I help

**Comment by greyshirtguy** [comment]
I've got a few lines of Python code working last night on my Mac that can send a KeyDown message to a specific process (whether it is foreground or background).   It was really fun to have Pro6 running in background and trigger a slide with a hotkey....
I'll finish some deigen ideas, tidy it up and do some testing etc and probably create a pull request for a new feature in VICREO module to send KeyDown to specific process (by name)

**Comment by JeffreyDavidsz** [comment]
Cool!
