### ISSUE TITLE
[BUG/CRASH] ProPresenter won't connect

### ISSUE THREAD

**Issue by ScottGlascock** [bitfocus/companion-module-renewedvision-propresenter#24]
**Describe the bug**
ProPresenter module not functional. Will not connect (Status never changes to OK)

**To Reproduce**
Make a button to control ProPresenter. When you push a button, red error square on stream deck surface lights up, "error" shows up in instance status. The buttons I've been creating/testing are "Next Slide" and "Clear All Slides"

** Updated with More Info **
No error in log, and when I hover over the error status in the instance page, i get [object Object].

**Comment by ScottGlascock** [comment]
Has anyone looked at the broken ProPresenter module in 2.0?

**Comment by SteveTherrien** [comment]
I just successfully tested the latest 2.0 build with ProPresenter 6.5 (Mac) and 6.1.6.2 (Windows). They both connected and I can control ProPresenter as expected.

@ScottGlascock and @Stew-Smith, are either of you running Companion and ProPresenter on the same machine?

**Comment by Stew-Smith** [comment]
My test environment was using the local network on the same machine

On Nov 9, 2019, at 6:45 PM, Steve Therrien <notifications@github.com> wrote:

﻿

I just successfully tested the latest 2.0 build with ProPresenter 6.5 (Mac) and 6.1.6.2 (Windows). They both connected and I can control ProPresenter as expected.

@ScottGlascock<https://github.com/ScottGlascock> and @Stew-Smith<https://github.com/Stew-Smith>, are either of you running Companion and ProPresenter on the same machine?

**Comment by SteveTherrien** [comment]
It looks like code was added to prevent connections to the loopback adapter (`127.0.0.1`) to solve a different bug. I'll submit a fix later tonight.

A temporary workaround would be to connect to your computer's actual IP (it's probably something that starts with `192.168.`) instead of `127.0.0.1`.
