### ISSUE TITLE
Remote application protocol out of date.

### ISSUE THREAD

**Issue by alexclaas** [bitfocus/companion-module-renewedvision-propresenter#28]
Hi guys,

Trying to connect Companion 1.4 to ProPresenter 7 with the ProPresenter module and I'm having some issues. I'm wondering if I'm just missing something simple or thinking about it the wrong way. I set up the Network controller and passwords in ProPresenter. In the Companion module config I tried both 127.0.0.1 and my computers IP address and I'm receiving the error message "Remote application protocol out of date.". I'm wondering which protocol it's saying is out of date? As far as I can tell all the software related is up to date, is the problem possibly that the version of ProPresenter I am using is too new? It's ProPresenter version 7.0.2 (117441028). It's all being done on the same computer. Feel like I'm doing the set up correctly but I'm missing something silly that's messing me up, let me know if there's anything I can try or further information that could be helpful. Thanks!

-Alex

**Comment by bicheichane** [comment]
Bump. I'm also having this issue. 
Using Companion 1.4.0 and pro presenter 7.0.4 all on the same pc.

**Comment by josephdadams** [comment]
If you want to use Companion with Pro7, you need to be running Companion 2.0. There haven’t been any updates to 1.4 since it came out.

**Comment by alexclaas** [comment]
Ahhh I see, I figured it was something silly I was missing, thank you
Joseph!

**Comment by bicheichane** [comment]
@josephdadams I am completely new to companion, and I used the website to download it, not github. 1.4.0 is the prominent version there, didn't even notice there was a 2.0 until you mentioned it! Thanks for the help
