### ISSUE TITLE
Pro7 Stage Display Change Crash [BUG]

### ISSUE THREAD

**Issue by seanathonedward-therock** [bitfocus/companion-module-renewedvision-propresenter#29]
**Describe the bug**
Using change Stage Display actions with more than one stage display connected crashes Pro7

**To Reproduce**
1. Create button the changes stage display
2. Push button
3. Crash Pro7

**Expected behavior**
Button should do as it says

**Desktop (please complete the following information):**
 - OS: Mac 10.15
 - Browser [n/a]
 - Companion Version [e.g. 2.0]

**Comment by haakonnessjoen** [comment]
Sounds like this should be reported to renewed vision. It’s not our fault that it crashes

**Comment by greyshirtguy** [comment]
I agree...
However, I was talking to Kyle in the FB group about this issue...
I could not re-produce it on my systems, so I was offering to remote in to his system to try and learn exactly what is causing it.....(I have had no response yet, as he is away and is probably still reeling in shock at the idea of giving remote access to a stranger!)

My thought was, that if we could nail down the precise cause and come up with repeatable steps to reproduce on any system - I would be able to take to the devs at RV and have a much better chance of them looking at fixing it!

**Comment by greyshirtguy** [comment]
Hey @josephdadams - This has been fixed in a previous commit - can you please close.
