### ISSUE TITLE
Propresenter 7 Config Error

### ISSUE THREAD

**Issue by timwowor** [bitfocus/companion-module-renewedvision-propresenter#30]
Keep getting this error message trying to connect to ProPresenter 7

24. 23:14:58 instance(propresenter2): Remote application protocol out of date. Update application

**Comment by MichaelAllen** [comment]
Make sure you are using a recent build of companion v2.0. The modules in v1.4 aren't receiving updates anymore. 

I am using companion v2.0 to talk with ProPresenter v7 and haven't had any issues.

Here is where you can find the download link: https://bitfocus.io/user/downloads
<img src="https://user-images.githubusercontent.com/282879/77471862-635bf580-6de9-11ea-8e9d-921d12a488a7.png" width=250 />

**Comment by timwowor** [comment]
Works great! Thanks Michael! Btw do you know how to remotely control ProPresenter/Vicreo using companion on another computer?

**Comment by MichaelAllen** [comment]
Assuming you have network connectivity between the 2 computers, it should be as simple as entering the ProPresenter computer's IP address into the module's settings page on Companion.  

If you are using Mac, that should be all you have to do. If you are using Windows, you may have to allow Companion through the built-in firewall.

**Comment by timwowor** [comment]
Both computers running companion and instances?

**Comment by MichaelAllen** [comment]
Companion would only need to be running on your control computer (the one that has the streamdeck connected). The computer with Propresenter/Vicreo would does not need Companion installed.

**Comment by greyshirtguy** [comment]
Hey @josephdadams - this one can be closed now too!
