### ISSUE TITLE
Propresenter 7 Crashes after when stage display cue is hit[BUG]

### ISSUE THREAD

**Issue by Cmillets** [bitfocus/companion-module-renewedvision-propresenter#31]
**Describe the bug**
I set up Pro7 on in companion(among other things). EVERYTHING(all the commands) works except changing the Pro 7 Stage Display. After set up......when you push the button instantly crashes pro7 and shows an error message(I will update with the message once I get in tomorrow)

**To Reproduce**

- Make sure Propresenter instance is created and working
- Add a button and create a command changing pro 7 stage display
- once it is set to the display you want test it
- It Instantly Crashes Pro7

**Expected behavior**
Change the Stage display in pro7

**Desktop (please complete the following information):**
 - OS: Mac 10.15.3
 - Browser: Chrome
 - Companion Version: Latest 2.0 version(as of 3/26/20

**Comment by greyshirtguy** [comment]
Sorry - I am aware of this bug...
I hope to fix soon...(it's been a crazy couple of weeks)
In the meantime there is a workaround that you can do now if you like...

Each time you add the pro7 action to set stage display,  For both stage display and screen drop-downs, set them BOTH to NON default options (2nd, 3rd 4th etc).  You can then set them back to first option if you like...  If you don't have a 2nd of either then you might need to make one some additional temporary ones to do this workaround...

Leaving either one default first option after first adding will cause this crash.

I will fix this soon (over next week)

**Comment by greyshirtguy** [comment]
Hey @josephdadams - can you close this - it's been fixed in a previous commit.
