### ISSUE TITLE
Add Clear Messages for Pro7

### ISSUE THREAD

**Issue by MarauderSeeker** [bitfocus/companion-module-renewedvision-propresenter#38]
Please add a Clear Message button, like Clear All, Clear Foreground, Clear Background.

**Comment by greyshirtguy** [comment]
Oh wow - we missed that!..
Will do...
I'll add it soon!

**Comment by greyshirtguy** [comment]
Done in my fork. When pull request 37 gets approved, this will be added to Bitfocus master.
https://github.com/bitfocus/companion-module-renewedvision-propresenter/pull/37

**Comment by greyshirtguy** [comment]
Merged - should be in next beta build.
