### ISSUE TITLE
Feature Request: Play Video clip button

### ISSUE THREAD

**Issue by 2peppe2** [bitfocus/companion-module-renewedvision-propresenter#39]
an option to have a button that plays the the currently selected video clip.

![Anteckning 2020-07-31 175208](https://user-images.githubusercontent.com/60645354/89052844-96456580-d356-11ea-8306-7802c5dd8769.png)

Basically I want to click that button but from the streamdeck. (from another computer)

This would make cooperation between our propresenter guy and ATEM guy much better when you can click one button and both the ATEM change input and propresenter plays the video clip.

Maybe there is a much better way of syncing the playing of a  clip with ATEM.

thanks beforehand

**Comment by Lucreativedesign** [comment]
This would be awesome!

**Comment by josephdadams** [comment]
Set Pro7 to listen to incoming RossTalk. Then just use the RossTalk module in Companion. If that video is selected in the playlist, send RossTalk action `NEXT`. Works great.

**Comment by josephdadams** [comment]
Companion does though. So you can essentially press that “play” icon in Pro7 (or 6) that way by pressing a button on the stream deck.

**Comment by greyshirtguy** [comment]
FWIW, the ProPresenter module can also send a NEXT to Pro7 (or Pro6) - This works for both Windows and Mac versions of ProPresenter. RossTalk would work - but only on Mac versions.  Pro7 on windows only suports MIDI or the remote protocol.
Also, note that for either of the solutions mentioned so far to work, the video has to be selected by the ProPresenter operator for the "NEXT" command to trigger it.

Ideally, it would be perfect be able to set a button to simply trigger an media item in the media bin, but, there is nothing in the remote protocol to trigger a media item in the media bin (I wish there was and I have asked RV to add in - but I imagine they have a huge lits of other items they want to work on before helping third party tools!)

You can however do this with RV's other product PVP (this is really it's "wheelhouse")

**Comment by greyshirtguy** [comment]
hmm... I'd be tempted to try and setup @josephdadams  https://github.com/josephdadams/midi-relay and use https://github.com/bitfocus/companion-module-techministry-midirelay to send MIDI commands to ProPresenter to select the Media Bin Playlist and then trigger a Media cue...
I havent used that before - I might have  play and figure out the indexing (using note values)

**Comment by themediaguy1297** [comment]
That's true. I didn't even think about it in that since. That's a great idea.

**Comment by josephdadams** [comment]
@greyshirtguy I seem to recall someone here doing that with midi-relay and it worked!

**Comment by greyshirtguy** [comment]
You can now trigger media items in the media bin if you have Pro 7.8 or higher with Network Link enbabled in preferences.
The latest beta builds of Companion have new (beta) actions that use this new API.
The a great addition is the ability to trigger media using it's name (and the name of the media bin playlist that it is in!)
![image](https://user-images.githubusercontent.com/1886513/150782250-0f10e80e-7e08-49de-afbe-9228ecfb6abd.png)
