### ISSUE TITLE
Feature Request: ProPresenter Hot Key

### ISSUE THREAD

**Issue by EnerGiehl** [bitfocus/companion-module-renewedvision-propresenter#5]
**Describe the feature**
I'd like to use the Hot Key function to trigger slides. Yet it's only possible to trigger by number to a specific slide not by letter. (or maybe a regular macro/hotkey module?!)

**Is this platform dependent (windows, mac, ..)?**
no

**Comment by greyshirtguy** [comment]
In the interim, you might want to try a patched version of Octopus Listener I made that sends **Command** modified keystrokes when told to send **Control**.
https://www.dropbox.com/s/bxputx58p1kfv6x/Octopus%20Listener%20%28Patched%20So%20Control%20is%20Command%29.app.zip?dl=0

**Comment by JeffreyDavidsz** [comment]
@greyshirtguy do you have the sourcecode? I have a newly build listener ready, but not for MAC yet. Some fixes in the octopus listener would help people as well

**Comment by greyshirtguy** [comment]
I don't have the source... I checked out the executable with a HEX editor and got lucky - the MacOS listener uses AppleScript to send the keystrokes and that made it easy to patch "control" to "command".

I was thinking about writing a simple listener (for keystrokes to system and/or specific apps) - glad to hear someone else is already *before* I wasted too much time getting started.. (I had only just started to do a little research into the MacOS side of things)

**Comment by JeffreyDavidsz** [comment]
@greyshirtguy clear! I've a module in Companion which called VICREO Hotkey. Just uploaded a MAC version at https://github.com/JeffreyDavidsz/VICREO-Listener/releases The MAC version is not graphical yet but it should work. Maybe you like to test it? Just download and run.

**Comment by JeffreyDavidsz** [comment]
@EnerGiehl  @chrisrouse try the VICREO Listener I've written this because the octopus listener is not supported by the author. Still early stage but try it! https://github.com/JeffreyDavidsz/VICREO-Listener/releases let me know if it works for you

**Comment by chrisrouse** [comment]
@JeffreyDavidsz How does it connect with Companion?

**Comment by JeffreyDavidsz** [comment]
I've created the vicreo-hotkey module for that.

**Comment by greyshirtguy** [comment]
> @greyshirtguy clear! I've a module in Companion which called VICREO Hotkey. Just uploaded a MAC version at https://github.com/JeffreyDavidsz/VICREO-Listener/releases The MAC version is not graphical yet but it should work. Maybe you like to test it? Just download and run.

Thanks - sounds awesome!
I just logged an issue (Can't connect to Mac listener from other machines on network)
Easy fix is included in issue description.

**Comment by JeffreyDavidsz** [comment]
You can use the VICREO-Hotkey module for this
