### ISSUE TITLE
Remote application protocol out of date. Update application

### ISSUE THREAD

**Issue by blinkielight** [bitfocus/companion-module-renewedvision-propresenter#53]
My Pro7 is not connecting on my pro7 computer or a different computer. All setting is correct. The only error I'm getting is "Remote application protocol out of date. Update application"

**Comment by greyshirtguy** [comment]
Hello @blinkielight 
Are you running the current version of Companion? (Which exact version?)
What is the exact version # of Pro7 that you are running?
Is it the MacOS or Win version of Pro7?

**Comment by greyshirtguy** [comment]
Found it!
It's the new 7.4.2 **Beta**, now requires an updated remote client (which is what the Companion module is in effect).
It's a just a version check - and a refusal to let "old" clients connect.
I'll update the client version in the module to fix this (I'll actually make it a config item where you can easily edit the version in future without needed a new Companion version installed)

**Comment by RedZephon** [comment]
> Found it!
> It's the new 7.4.2 **Beta**, now requires an updated remote client (which is what the Companion module is in effect).
> It's a just a version check - and a refusal to let "old" clients connect.
> I'll update the client version in the module to fix this (I'll actually make it a config item where you can easily edit the version in future without needed a new Companion version installed)

Has this been deployed? Im also facing this issue.

**Comment by greyshirtguy** [comment]
It was added to developer builds a few weeks ago - For now, you will have to run a dev build:

![image](https://user-images.githubusercontent.com/1886513/110717922-15d8d280-825e-11eb-8f5f-2a980ba52f2d.png)

Sorry - I don't know when the public build will be updated to include new changes!

**Comment by greyshirtguy** [comment]
Whoops - my bad... I have not updated to support Pro7.4.2 yet!
I will add this soon.
Again, sorry everyone - I have updated code in my fork - and I thought I had commited this back to BitFocus.

**Comment by RedZephon** [comment]
> Whoops - my bad... I have not updated to support Pro7.4.2 yet!
> I will add this soon.
> Again, sorry everyone - I have updated code in my fork - and I thought I had commited this back to BitFocus.

Do you know when this would be ready for use? We've been using 7.4.2 since 7.4.1 is terribly broken for us.

**Comment by greyshirtguy** [comment]
I'll try and get this working code commited in the next day or two...
I'll update here to let you know

**Comment by greyshirtguy** [comment]
Latest BETA builds fix this issue.
