### ISSUE TITLE
Store Slide - Go Back?

### ISSUE THREAD

**Issue by Newyears1978** [bitfocus/companion-module-renewedvision-propresenter#54]
Curious if a function could be added that would save the current slide path (however possible. If at all? Like similar to how you can go to a specific slide wtih the presentation path like Slide 3 Path 0:1 etc)

Unfortunately a lot of things in PP are funky and can't be used properly. We're currently building Lower thirds labels for staff members who come up during our service. The RIGHT way to do it would be to set them up as Prop but since Renewed Vision did not setup any API for Props at all it can't be used with Companion. So we used messages, and it worked but it is super sloppy and sometimes PP decides to stop showing messages properly. 

The way I set it up is that hitting a stream deck button would show that message and hitting it again would clear messages. 

So my thought was to just make a document that houses all the lower thirds with the prebuilt names - the issue is doing that gets me "out of place" in the current playlist and it would be a hastle to have to try to click back.

Soooo my thought (TLDR) was a function that when you hit it, it reads the current slide path, and stores it. So it would say okay you're on slide such and such. Then I would add my go to specific slide and then on toggle off go back to stored slide.

Is this doable?

Or is there some better way to do this that I am missing?

Sorry long winded...frustrated with PP today.

**Comment by greyshirtguy** [comment]
I am naively hopeful that the remote API will be updated to support triggering Props some time this year!
Also, you can trigger props on/off with MIDI in ProPresenter - Using MIDI-relay module with Companion would enable you to send the right MIDI notes to control Props from StreamDeck.

That said - Perhaps a new action, "go-to-previous-slide" might be useful...(maybe)...

**Comment by tacvideo** [comment]
Any movement on this idea, I too was looking for this functionality - to put up worship leaders names?

Got excited when I stumbled into a BETA feature to store variables, and asked about the Tab I couldn't see :)

Anyhow, we're fortunate enough to have a BlackMagic ATEM where I can store a bunch of media files (exported slides from PP as a PNG with names), and with a special page on the Streamdeck for Titles I can pull up any of our regulars names using DSK on the ATEM, not too efficient but it works for now ;)

**Comment by greyshirtguy** [comment]
Super close... just tidying up some minor bugs...
and then we will have a beta build fo you to test

**Comment by greyshirtguy** [comment]
Latest beta builds have all that you need!
1. If you have Pro 7.8 (or higher) and enable Network Link feature - You can now trigger or clear specifc Props (by name) with new actions that use the network link feature. (Look for actions with "Network Link - Beta" in their name)
2. You can now use custom variables in the "Specific Slide" action fields for "Slide Number" and "Presentation Path".
Combining that with Companion custom variables and you can store the current slide number and path in two custom variables and then use those custom variables in a "Specific Slide" action to recall that stored slide. (you prob wont need this any more - now that you can work directly with props! - but it still might be a useful feture for other use-cases)
