### ISSUE TITLE
Companion connected to ProPresenter 7.4.1 (117702927) crashes ProPresenter

### ISSUE THREAD

**Issue by goroguedesigns** [bitfocus/companion-module-renewedvision-propresenter#55]
I've been using Companion for about a year with ProPrsenter 7 and have not had any issues whatsoever. This last Sunday, every time I ran ProPresenter and then started Companion it would automatically crash ProPresenter. I thought ProPresenter was the culprit till I uninstalled it and reinstalled it 5 different times. I tried installing older ProPresenter 7 builds to see if it fixed my issue, but it didn't. I finally noticed a pattern that if I had companion running (auto connects by IP to ProPresenter) and tried to start ProPresenter, it would kill it after 5 seconds. Then I disabled the connection with ProPresenter in Companion and the ran ProPresneter and then enabled the connection in Companion and it would kill it. I tried updating to the new developer build of Companion to see if that would fix the problem but it didn't. Only other thing I can think of is a stupid windows 10 update that changed something with the network protocol.

This is my setup -
ProPresenter 7 is run on a windows 10 PC
Companion is ran on a Windows 10 Laptop.

I use a Stream Deck with Companion along with OBS. At the press of a button I can trigger a scene in OBS and a specific slide in ProPresenter.

**Comment by greyshirtguy** [comment]
Aaah yes -that old chestnut!

It took me a while to figured it out a long time ago...
And took me a while to remember the details....

It's an issue/bug/intentional behaviou? in ProPresenter itself!

If you enable networking......but disable "ProPresenter Remote"
Pro7 will crash when a remote client (like Companion module) tries to connect to it.

![image](https://user-images.githubusercontent.com/1886513/112290293-30da2680-8ce3-11eb-9b98-ba74bfdc6cb4.png)


Only workaround is to check "Enable ProPresenter Remote"

(To get out of the crash at load jail, disable the Companion module first)

**Comment by goroguedesigns** [comment]
Thanks for the reply.

I figured it was more than likely ProPresenter being the culprit.
I have already had Network and Remote enabled.

My setup, which I hope to eliminate this Sunday since we are getting a NDI PTZ Cam, is Companion running on another computer that uses the remote feature to send commands. It randomly stopped working for whatever reason.

I was able to remote into my ProPresenter computer that happens to have Companion setup the same way as my other computer. I did find a pattern with ProPresenter crashing. If I open ProPresenter and then Companion, it will crash ProPresenter. If I open Companion and then open ProPresenter, then it will run without an issue. At least this is a potential work around when I try my new setup on Sunday.

With the current 2 computer setup, if Companion is running and ProPresenter is opened it will crash ProPresenter in 5 seconds. If ProPresenter is open and then I open Companion, it crashes ProPresenter immediately.

Here are some screenshots that I haven't changed for a year.
![companion](https://user-images.githubusercontent.com/51349211/112348541-29843000-8c85-11eb-8e55-f27c1e51f14b.JPG)
![pp](https://user-images.githubusercontent.com/51349211/112348586-32750180-8c85-11eb-986f-7d94f26a7246.JPG)

**Comment by greyshirtguy** [comment]
Ohh sorry - there must be more to the story.
I just did a test and found it also crashes when it tries to connect to stage App.
I vaguley remember an the module trying the Stage-App connection anyway (even if you say no in the config)...
As a test-and-learn, can you please enable stage app?

**Comment by goroguedesigns** [comment]
Enabling the Stage Mode on both Companion and ProPresenter did the trick. Thanks for the help! I greatly appreciate it. I never would have figured it out.
