### ISSUE TITLE
7.4.2 pro presenter error

### ISSUE THREAD

**Issue by RylandRussell** [bitfocus/companion-module-renewedvision-propresenter#59]
Hey there, the new release of Pro seems to cause a connection issue.  Any ideas?
<img width="1386" alt="Screen Shot 2021-03-30 at 6 07 06 PM" src="https://user-images.githubusercontent.com/68162070/113067924-e2190a80-9182-11eb-9f04-7ced07daf2a3.png">

**Comment by greyshirtguy** [comment]
Latest BETA builds fix this issue!
