### ISSUE TITLE
Propresenter 7.4.2 and companion-2.2.0-ed646365-3202-win64.exe crashes on same PC

### ISSUE THREAD

**Issue by cramaboule** [bitfocus/companion-module-renewedvision-propresenter#60]
Hello,

I updated Propresenter 7.4.2
updated my companion to companion-2.2.0-ed646365-3202-win64.exe (beta)

I launch Propresenter on W10 pro x64  20H2 (Swiss French)
then, when I launch companion, PP7 is crashing.

Same issue with companion-2.2.0-b98a0622-3203-win64.exe (beta)

Works well on two different PC.

**Comment by greyshirtguy** [comment]
I am aware of the two following conditions that can cause this behaviour.

1. Disable ProPresenter Remote, while Network is enabled. Pro7 will crash when Companion module tries to connect.
![image](https://user-images.githubusercontent.com/1886513/113219278-d20d4200-92cc-11eb-86b2-4aff372aed66.png)

2. Disable Stage App while Network is enabled and Companion ProPresenter module is configured to connect to stage display
![image](https://user-images.githubusercontent.com/1886513/113219534-46e07c00-92cd-11eb-9c1f-a75784dcd6c2.png)

Workaround:
In Pro7 prefs:
1. Make sure ProPresenter remote is enabled always
2. Make sure Stage App is enabled if you select Yes for Companion modue to connect to stage display.

**Comment by greyshirtguy** [comment]
Going to close this - as the _issue_ is not with the Companion module - but rather built-in behaviour of Pro7 itself.
Basically Pro7 will crash if Companion (or a remote client) tries to connect with those options disabled.
