### ISSUE TITLE
Problem connecting to Propresenter

### ISSUE THREAD

**Issue by umpmanjoe** [bitfocus/companion-module-renewedvision-propresenter#61]
Turned on my computer and I'm getting this error in companion. 31. 16:12:08 instance(propresenter): Remote application protocol out of date. Update application

There was an update to pro presenter today but I even tried downgrading to the previous version and still not working,

I'm on the correct network and have the right port

**Comment by greyshirtguy** [comment]
The latest BETA builds fix this issue!
