### ISSUE TITLE
"Remote application protocol out of date. Update application" on ProPresenter 7.4.2 (117703185)

### ISSUE THREAD

**Issue by justingiffard** [bitfocus/companion-module-renewedvision-propresenter#63]
Getting no connection (or it thinking it has connection until you try do an action) since updating to ProPresenter 7.4.2 (117703185)

Instance status says "`ERROR`" and sometimes says "`OK, But Stage Display closed`"

``` instance(propresenter): Remote application protocol out of date. Update application```
``` instance(propresenter): ProPresenter Stage Display Disconnected```

When starting up Companion I get the following in log:
`02. 11:44:37 instance(propresenter): ProPresenter Stage Display Connected`
`02. 11:44:37 instance(propresenter): Stopping ConnectionTimer`
`02. 11:44:37 instance(propresenter): Remote application protocol out of date. Update application`
`02. 11:44:37 instance(propresenter): Opened websocket to ProPresenter stage display: 127.0.0.1:20562`
`02. 11:44:37 instance(propresenter): Opened websocket to ProPresenter remote control: 127.0.0.1:20562`

Instance status says "OK" then the moment I trigger any action (e.g. next slide) the button gets the red block and instance status turns to "ERROR"

Also all variables are `"N/A"` except for `$(propresenter:connection_status)` which is `"Disconnected"`

**Comment by mhohman** [comment]
Same issue here on 5 installs.

**Comment by greyshirtguy** [comment]
Hello everyone.
This issue is fixed in latest beta builds
