### ISSUE TITLE
Remote application protocol out of date. Update application

### ISSUE THREAD

**Issue by corneels** [bitfocus/companion-module-renewedvision-propresenter#65]
ProPresenter 7.4.2
Companion 2.1.2-f4bcaf3-2679

Module was working previously. This started happening after updating ProPresenter to 7.4.2.

I get this error: `Remote application protocol out of date. Update application`

ProPresenter and Companion are both up to date.

**Comment by greyshirtguy** [comment]
The latest BETA builds of Companion fix this issue.
Until a new production release is made that includes the fixes, you will have to use the BETA builds.

**Comment by corneels** [comment]
Thanks mate

**Comment by greyshirtguy** [comment]
Ooohh you said "mate"..

Yep just checked... a fellow Auzzie!
G'day!!!

**Comment by corneels** [comment]
G'day!!

Thanks for putting up with repeated issues on the same thing... Lesson learned will check the closed tab next time ;)

Installed the beta and she's good as.
