### ISSUE TITLE
instance(propresenter): Remote application protocol out of date. Update application

### ISSUE THREAD

**Issue by jjbutler83** [bitfocus/companion-module-renewedvision-propresenter#66]
Running the latest version of Companion Pi (RPi4 machine) Have used ProPresenter modules successfully with this machine before. Now when attempting to access a fresh install of ProPresenter 7.4.2 (117703186) on a MBP running Catalina with latest updates, I get the message: "instance(propresenter): Remote application protocol out of date. Update application"

Companion is up to date and ProPresenter is the latest version.
All IP/port information has been entered correctly.

Only other possible factor is ProPresenter is not licensed, I am simply using it as a test/show build machine at this time.

**Comment by greyshirtguy** [comment]
The latest BETA builds of Companion fix this issue.
Until a new production release is made that includes the fixes, you will have to use the BETA builds.
