### ISSUE TITLE
Next Slide will not scroll slides display (Beta)

### ISSUE THREAD

**Issue by hparsons56** [bitfocus/companion-module-renewedvision-propresenter#67]
Using ProPresenter 7.4.1 (church) and 7.4.2 (home), and beta version companion-2.2.0-7309b8c1-3214-win64.exe of Companion, both machines are Windows 10. 
The "Next Slide" function does not advance the scroll on the slides display in ProPresenter if you are on the bottom row of the slides (and there are more slides off view).
Using the keyboard arrow key advances the scroll properly. Also, using Vicero Hotkey (in Companion) to emulate the arrow key advances the scroll properly. The Next Slide function does not.

**Comment by greyshirtguy** [comment]
This behaviour is built into Pro7 itself - It would require Renewed Vision to update Pro7 to make a change to how it scrolls when a remote client sends "Next Slide". Interestingly the Mac version of Pro7 does scroll!
I'm not sure which way they will go - I have heard they are looking into it.  I don't know, but I suspect it's low priority for them.
