### ISSUE TITLE
Remote application protocol out of date.

### ISSUE THREAD

**Issue by crackley** [bitfocus/companion-module-renewedvision-propresenter#69]
Running ProPresenter 7.4.2 on a Mac and Companion 2.1.2, I can't connect. I am receiving the error "Remote application protocol out of date. Update application."

**Comment by greyshirtguy** [comment]
Hello!
Please note that the latest BETA builds of Companion fix this issue.

Until a new production release is made that includes the fixes, you will have to use the BETA builds.
