### ISSUE TITLE
Enable/Disable props in ProPresenter 7 module

### ISSUE THREAD

**Issue by mrlad** [bitfocus/companion-module-renewedvision-propresenter#71]
If the protocol allows it, please offer the option to enable/disable props in ProPresenter 7 module

**Comment by josephdadams** [comment]
@greyshirtguy ?

**Comment by greyshirtguy** [comment]
Nothing to control specific props in the remote protocol presently - So only optoin is with MIDI - It works great using MIDI-Relay !!!

I have tested this on both Win and MacOS.

**Comment by greyshirtguy** [comment]
For what it's worth - I have hounded the poor RV devs about future features in the remote app - but could not get anything concrete! However, they use wording in their replies that gives me some (perhaps naive) hope that we might see some new features/improvements in the ability to remote control ProPresenter.
