### ISSUE TITLE
Feature Request: More Timers as variables

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-renewedvision-propresenter#73]
Would it be possible to bring back more timers as variables, not just the 'watched' timer setup in the config screen?

**Comment by greyshirtguy** [comment]
Yes!!! I will do this. (in next week or two)
I've been recently thinking about doing this! Thanks for the "nudge".
(Will also make better dynamic vars to display timers)

**Comment by jmcc94** [comment]
Thanks.

Also if possible, bring through all the stage display names and their layouts as variables - not just the 'monitored' one on the config screen

**Comment by Gossamer-the-1st** [comment]
Hello greyshirtguy!
I am in all ways new to the programming side of things, so thank you for your patience ahead of time. I am able to get a Companion button to show one of our countdown timers from ProPresenter 6, but am in need of being able to show a secondary countdown timer. Been trying to get this worked out for a couple months and just now came upon this request from jmcc94. Have you had any chance to get this to a working stage? If so, how would I go about getting this applied to our Companion app running on Mac OSX? I appreciate any info and many thanks for the great job you all have already done on the ProPresenter workings..!

**Comment by ErikGundersen** [comment]
There is a a work around, You can have Multiple Instances of Propresenter installed on Companion with different watched Timers. and then use the unique instance name on the timer.

**Comment by Gossamer-the-1st** [comment]
Hmmm. That is an interesting work around as we do have 2 instances of ProPresenter 6 running.  I'll have to give that a test when things lighten up after Christmas.

Thank you Erik!!

**Comment by greyshirtguy** [comment]
Sorry this took so long
It's in the latest beta builds now.

The latest beta introduces new clock variables for getting the value of ANY timer/clock.
You are not longer restricted to just selecting a single watched clock!

(I have left the watched clock as it is - in case other users are expecting it to NOT change.).

You can now start using the new vars for clocks.
There are TWO dynmaic variables for every timer/clock...

`pro7_clock_n` _(where n = the index of the clock)_ - this will always return hh:mm:ss
`pro7_clock_n_hourless` _(where n = the index of the clock)_ - this will always return mm:ss

Indexes are zero based
eg 
pro7_clock_0 is the first clock in hh:mm:ss format
pro7_clock_1_hourless is the second clock in mm:ss format

**Comment by greyshirtguy** [comment]
@jmcc94 

<html>
<body>


$(propresenter:StageScreenName_pro7_stagelayoutname) | The name of the current stage-display layout on the stage screen with name: "stageScreenName" (Case Sensitive)
-- | --



</body>
</html>
