### ISSUE TITLE
Feature Request: Next/Previous Playlist item

### ISSUE THREAD

**Issue by SimonK34** [bitfocus/companion-module-renewedvision-propresenter#76]
Would it be possible to add next and previous playlist items like the ones available when using MIDI?

**Comment by greyshirtguy** [comment]
I don't think there is any command in the remote protocol (used by Companion) to select a playlist or playlist item (without triggering a slide). There is however, a command to trigger any slide from any item in any playlist.
That said, did you know there is another module available in Companion called "Midi Relay".  If you add that module to Companion  and it's accompanying listener app - you can setup buttons to send any MIDI notes to ProPresenter and get access to some of those actions unique to MIDI control (like playlist selection and Props control)

**Comment by SimonK34** [comment]
Thank you for the quick reply. I'll have a look into the MIDI  relay.
