### ISSUE TITLE
Feature Request: Macros

### ISSUE THREAD

**Issue by themediaguy1297** [bitfocus/companion-module-renewedvision-propresenter#78]
When will Macros be added to this module? https://renewedvision.com/propresenter/whats-new/

**Comment by Marshy2006** [comment]
If it gets added to the ProRemote app, it will be added to the companion module.

**Comment by greyshirtguy** [comment]
Spoke to one of the devs at RV last night......
They have agreed to update the remote protocol just so Companion can do this !
_They said will get Pro7 updated first (for Companion) and will update the remtoe later!!! we may even get this before the remote app is even updated to support it!_
I'll be working on this the *moment* the new beta comes out.

**Comment by greyshirtguy** [comment]
**Update:** It was added to most recent Mac beta!!!!

I did some testing and found some issues which they are working on!
I'm excited to see this one get sorted and added to the module!

**Comment by themediaguy1297** [comment]
Awesome Dan, thanks for working on this bro!

**Comment by greyshirtguy** [comment]
Latest beta builds support triggering Macros (and Looks!)
