### ISSUE TITLE
Would be great if Companion also can work with the new Macros in ProPresenter 7.6

### ISSUE THREAD

**Issue by MrTeslaM3** [bitfocus/companion-module-renewedvision-propresenter#83]
Usecases for us

We change over the macros our Screen Layouts and also trigger / set different timers 

**Describe the feature**
A clear and concise description of what the feature does

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by greyshirtguy** [comment]
It's already done. The latest developer build adds button actions to trigger Macros and Looks.
(New features are only added to beta/developer builds - which eventually become new release builds)
