### ISSUE TITLE
Windows - When when press boton, propresenter follows on the playlist

### ISSUE THREAD

**Issue by miguelcosta85** [bitfocus/companion-module-renewedvision-propresenter#84]
In mac, I used to have a streamdeck key to trigger different slides (one goes to one output e another one goes to another output at the same time). With this trigger, the propresenter in mac don't change the playlist following the trigger. Just stays where it is.

When I used the same setup for windows, propresenter is following the slides that streamdeck triggers changing the playlist.
The problem is, as I have two different slides in two different playlist on the same botton, propresenter starts having a lot of lag changing slides in Propresenter trying to go to different playlists at the same time.

**Comment by greyshirtguy** [comment]
Sorry my friend - this is the intrinsic behaviour of Pro7 on Windows. Unless RV change it - this is how it is!
