### ISSUE TITLE
Props or Macros add-on

### ISSUE THREAD

**Issue by krisprince** [bitfocus/companion-module-renewedvision-propresenter#85]
Hi! 

Any chance we can get access to props or macros, outside of clearing, to be used for livestreaming? We use macros in PP7 for all of the lower thirds but would rather have a video producer utilize a streamdeck for the Lower Thirds needed.

Thanks!

**Comment by krisprince** [comment]
I apologize - I missed the closed issue from last year saying this was not possible. Have there been any updates regarding props? I was ale to find the API info for custom actions and Macros. I might have to create Macros for each lower third and go about this that route. Thanks.

**Comment by greyshirtguy** [comment]
No update in the API to support Props yet. (FWIW: I have not given up hope - based on convos with RV devs - I think its possible we may see it this year).

For now two options are:
1. Use MIDI-relay module (with the MIDI-Relay application running on Pro7 machine) to trigger specific props
2. Use Macros - one for each Prop you want to trigger (or specifically clear without a ClearAllProps)
