### ISSUE TITLE
Revised Path Index Graphic

### ISSUE THREAD

**Issue by Xylopyrographer** [bitfocus/companion-module-renewedvision-propresenter#88]
Clarified the graphic used to illustrate path naming in a playlist.

Suggest renaming "Presentation Path" to "Presentation Index". If it helps, the attached HELP.md file has this wording changed.

Thanks for this module!
![specific-slide-playlist-indexing](https://user-images.githubusercontent.com/81269441/137562449-296cd16b-9acd-46e8-97f2-00a8331bfcce.png)
[HELP.md](https://github.com/bitfocus/companion-module-renewedvision-propresenter/files/7356298/HELP.md)

**Comment by greyshirtguy** [comment]
Thanks so much!!!
I feel terrible... I know there is SOO much room for improvement in the doco. I have so many good ideas on what needs to be done to make it clearer/nicer and more user friendly and I've been meaning to do it! - But I've let other things always take priority! I really must work on that before the next big release!

For now, this is a wonderful help!

**Comment by Xylopyrographer** [comment]
You’re very welcome.

FWIW, I found the docs pretty good, just the path thing had me scratching my head a bit :)

Might want to add that the module doesn’t support Hot Keys in a presentation.

Thanks again for making this available!

Cheers,
    Xylo
===================

On Oct 15, 2021, at 4:57 PM, greyshirtguy ***@***.***> wrote:


Thanks so much!!!
I feel terrible... I know there is SOO much room for improvement in the doco. I have so many good ideas on what needs to be done to make it clearer/nicer and more user friendly and I've been meaning to do it! - But I've let other things always take priority! I really must work on that before the next big release!

For now, this is a wonderful help!
