### ISSUE TITLE
select playlist by name

### ISSUE THREAD

**Issue by JosephDesigns** [bitfocus/companion-module-renewedvision-propresenter#90]
**Describe the feature**
Currently the app allows user to use Specific Slide by slide number and item/presentation number.  It would be nice to select the presentation and playlist by name rather than by number.
**Usecases**
This would be more flexible as presentation order in a playlist are often re-arranged and not static.  In a giver church service, all the elements are practically the same but the order sometimes gets re-arranged from one week to another.

I appreciate your consideration.

**Comment by greyshirtguy** [comment]
I would love to add this feature!
Unfortunately, the current remote API does not offer the required feedback/actions to implement this feature.
I've been talking to Renewed Vision and they are planning to extend the API soon.
Let's see how things go over the next few months!

**Comment by greyshirtguy** [comment]
Still thinking about this...
It might actually be possible if I first query the complete playlist, parse the results for the matches names, extract the presenatation path and send that _every time the action is triggered_

This is a crazy idea from a performance perspective.....but it might work fine on quicker machines....
I'll test this idea out!

**Comment by JosephDesigns** [comment]
Can't wait to test it for you

**Comment by tacvideo** [comment]
This would be a useful feature for sure! 
Recently our team started toying with splitting our worship and moving Announcements to the middle somewhere and changing from 4 to 5 songs on some weeks, so I redesigned my PP playlists with Section headers, and put Worship at the end of the playlists so I don't have to reprogram buttons no matter where they want announcements or how many worship songs there are...

**Comment by greyshirtguy** [comment]
Great news.  in the new network link API there is ability to trigger a slide using the playlist name and presentation name!
RV have warned me the new API is still not finalised and to wait a few months for that.
By then, it will be trivial to add this new feature request

**Comment by greyshirtguy** [comment]
Hmm, I just realised, telling you all that it's going to be another few months is not really "great" news....(maybe just "good").
_I was just excited this is finally possible to do properly without the hack I mentioned earlier above._

I might add this feature now, using the new network API, as a "BETA" action with the disclaimer that it may stop working for a few weeks (until I fix it) when you upgrade Pro7.

**Comment by greyshirtguy** [comment]
Latest beta builds Companion have new actions added that use the new Network Link API in Pro7.8 (and higher).

If you have Pro7.8 (or higher) and you enable the Network Link in Preferences - you can use these new actions to trigger slide (and other items) by NAME!

I have marked (named) the new actions as "BETA" - but I think they are safe enough to try out and use.
