### ISSUE TITLE
subtract time

### ISSUE THREAD

**Issue by samuelbailey123** [bitfocus/companion-module-renewedvision-propresenter#91]
When using $(propresenter:watched_clock_current_time) you cannot use the 'dynamic' variable with anything else.

For example it would be a great idea to subtract time off of the timer using this variable '- 30' to shave off 30 seconds. But it is not supported and throws an error.

**Comment by samuelbailey123** [comment]
Here's another example if I try 
$(propresenter:watched_clock_current_time - 30) 
It throws $NA instead of the current time minus 30

**Comment by estilles** [comment]
@samuelbailey123, that's not possible in the current version of Companion. I submitted a couple of PRs to implement expressions with variables.

- bitfocus/companion-module-bitfocus-companion#43
- bitfocus/companion#1770

Once merged, it can be implemented in this module, but that will depend on the maintainers.

**Comment by greyshirtguy** [comment]
Lol - I was just (right now) searching Slack/Github to try and find out if Companion supported expressions!

**Comment by greyshirtguy** [comment]
@estilles 
Those are exciting PR's

**Comment by estilles** [comment]
@greyshirtguy 
It will if my PRs are merged. Fingers crossed.

**Comment by estilles** [comment]
@greyshirtguy ... There's been some progress. The PRs were merged, now we just need to wait for the updated module (`companion-module-bitfocus-companion`) be merged into the Companion Core.

**Comment by greyshirtguy** [comment]
P.S. @samuelbailey123 
The current time of a clock is not a single number (that you can add/subract from)...so this new expressions feature won't work for that.... 
I guess I'll have to add a new Action to specifically update a timer with a delta amount of time to add/subtract

**Comment by estilles** [comment]
Yeah ... my apologies. I wasn't aware of the format. I incorrectly assumed the clock was exposed in seconds (or maybe milliseconds).

**Comment by greyshirtguy** [comment]
I know this has been a while - sorry..
I plan to start work on this feature.

In the meantime, I have a question:

@samuelbailey123  Are you wanting to subtract time off the *current value of a running countdown timer* - OR off the duration of a countdown timer (that is not yet started)?

**Comment by samuelbailey123** [comment]
@greyshirtguy ideally I was wanting to subtract time from a running clock. 
But I think both options you listed would be great features

**Comment by greyshirtguy** [comment]
There seems to be no way to tell ProPresenter to change the value of a running timer.
All we can do is update the duration (to the current running time +- an input value), and then reset the clock and re-start it.
This means that this feature would re-define the duration of a contdown timer whenever it was used.
@samuelbailey123  you still want that?

**Comment by greyshirtguy** [comment]
At this point I thinking to use + or - prefix in either of the time update fields......
It will take the current value and add/subtract your inputed time and then UPDATE the clock to the new time.
![image](https://user-images.githubusercontent.com/1886513/150678928-1c42c4eb-13b2-48de-861c-c6ec3a0c40ee.png)

**Comment by samuelbailey123** [comment]
So it adds or subtracts a specific amount from the time and then restarts the timer? Want to make sure I'm under a correctly.

**Comment by samuelbailey123** [comment]
@greyshirtguy

**Comment by greyshirtguy** [comment]
Sorry not very good at explaining things using written text!
Here's a l[ive video demo](https://www.dropbox.com/s/kkrl7yawj9iiyuv/Add%20or%20Subtract%20Time%20Demo.mov?dl=0):.

**Comment by greyshirtguy** [comment]
@samuelbailey123 I have gone ahead and added this feature to the module.
This is in beta build -3803
Closing issue as the requested feature is now added (albeit as best as is possible with current API)
