### ISSUE TITLE
ProPresenter 7.7.1 not advancing Presentation or Main Window to current slide

### ISSUE THREAD

**Issue by tacvideo** [bitfocus/companion-module-renewedvision-propresenter#93]
When using "Specific Slide" or "Next/Prev Slide", the correct slides get "presented" to the outputs/preview, even if switching from a different Playlist, but the "selected"  Playlist and Presentation does not change at all... very weird, it's like flying blind.

Is this something specific to 7.7.1 (which is what's available as I just upgraded from 6.5.3 this week)? Is it a Bug or am I missing something?

I also checked I'm using Companion 2.1.3

**Comment by greyshirtguy** [comment]
It's specific to Pro7...
I think RV prefer it to work this way (which is why they added the "Show Triggered Presentation" Menu item in the Presentations Menu...
Let me have a think if we can work around it

**Comment by tacvideo** [comment]
"Show Triggered Presentation" is just the v7 language for "Show Library Selection" under Actions in v6, both use CMD+L, and not really helpful. We want to see the Triggered slide in the Presentation not the Library :)

**Comment by tacvideo** [comment]
This problem is specific to v7 (tried all old versions 7.3 and newer) and specific to Mac, works correctly on Windows 10 machine running v7.7.1

**Comment by greyshirtguy** [comment]
There is *no* remote control of this behaviour - we are at the mercy of how various pro7 versions *choose* to behave when a specific slide of a presentation is triggered remotely. (Try the same action in the mobile app)

**Comment by tacvideo** [comment]
Same behavior with their Remote app :(... odd thing is, there's a setting on the iPad app to "Follow Presentation Selection", that allows you to see on the iPad what presentation/slide ProPresenter is on, which works as expected. Opening a ticket with RV!

**Comment by tacvideo** [comment]
RV support have replicated the issue and escalated to their Dev team! Odd that nobody picked this up in over a year... 

will leave this open and update when they resolve(or if the moderators prefer they can close)

**Comment by greyshirtguy** [comment]
Because this behaviour is 100% within ProPresenter itself...(nothing Companion module can do)
I am going to close it
