### ISSUE TITLE
Timer Display Mac vs Windows - Dynamic Variables

### ISSUE THREAD

**Issue by ErikGundersen** [bitfocus/companion-module-renewedvision-propresenter#94]
It seems that the Mac (Mac Pro M1 Chip) is showing HH:MM:SS:MS, but Windows does not show the MS... 

The Windows Display of this looks and functions better, as Companion only refreshes that field once a second, so the Millisecond display doesn't change often.

Can the MS be removed from this variable as an option?

$(propresenter:watched_clock_current_time)

**Comment by KzBoy** [comment]
+1 to this. I also noticed that.
It requires the font to be quite small just to show information that isn't needed anyway.

**Comment by tacvideo** [comment]
Also just noticed this, but on an Intel Mac.

**Comment by greyshirtguy** [comment]
This is overdue!
I'll get onto this soon

**Comment by Gossamer-the-1st** [comment]
I'm not at our Intel Mac based ProPresenter 6 set up to look, but I know that when I am using $(propresenter:watched_clock_current_time) on a button, it does not show the MS. I'm thinking that is because in ProPresenter, the watched clock is not using the MS portion, as you can select the parts you want to see. I'll try and take a look at it tomorrow.

**Comment by greyshirtguy** [comment]
It all comes down to the fact that different versions of ProPresnter (6, 7.etc) on Mac and Windows send different values - some include the ms some do not.

The latest beta introduces new clock variables for getting the value of ANY timer/clock.
You are not longer restricted to just selecting a single watched clock!

(I have left the watched clock as it is - in case other users are expecting it to NOT change.).

You can now start using the new vars for clocks.
There are TWO dynmaic variables for every timer/clock...

`pro7_clock_n ` _(where n = the index of the clock)_ - this will always return **hh:mm:ss**
`pro7_clock_n_hourless` _(where n = the index of the clock)_ - this will always return **mm:ss**

**Comment by greyshirtguy** [comment]
New variables are tested and working well. Closing Issue.
