### ISSUE TITLE
Follower Bug's

### ISSUE THREAD

**Issue by KzBoy** [bitfocus/companion-module-renewedvision-propresenter#95]
UPDATED

Just started using the follower feature.. It's been AMAZING and a **huge** timesaver!! Thank you!!

I did notice two bugs.

1. It seems like index 11 for whatever reason is missed on the link. 
2. Index **1** requires a 2x click on the 'master' instance to trigger the 'slave' instance.

**Extended Info**
1. Basically within the playlist if you click through each presentation it will match up until you click on number 11 and for whatever reason it doesn't trigger the 2nd machine. After that one it will resume. Our quick hack to get it working is that we just added a header on both machines for index 11 to essentially 'skip' it. Since headers are basically blank index positions anyway. 
2. A single click on the first slide of each presentation on the __'master'__ instance triggers the corresponding presentation & slide on the __'slave'__ instance (with the exception of issue 1 described above that doesn't trigger at all). However when triggering the first presentation at index 1, the first click does nothing and the 2nd click triggers the __'slave'__ instance. 

Thanks again!

**Comment by greyshirtguy** [comment]
Looking forward to your update with more info!
In the meantime -did you see the new beta verion 7.8 has totally AMAZING master/slave (leader/follower) built in.
It's insane how much it controls..
This feature in Companion is moot!

**Comment by KzBoy** [comment]
That looks really nice! Thanks for the info.

I updated the issue above. Interestingly in both cases its an issue with an index ending in '1'. perhaps the issue is related to that digit being miss-calculated??

**Comment by greyshirtguy** [comment]
Hmm, I just tried to replicate this issue but I could not using recent Companion beta (dev) builds.
I used Pro7.8.1 on Windows 10 and Pro 7.8 on MacOS 12.0.1.
I tried _both ways_ with the Mac and Win machines taking turns in following - slides 1 through 15 all worked fine.
Is this issue still happening to you?
Can you share all the details?
* Companion version
* Companion Pro Modules settings
* Companion debug log (esp around time the wrong behaviour happens)
* Pro7 versions are both ends.
* IP address of both computers.

**Comment by KzBoy** [comment]
Well I went back to try it out and unfortunately while I did get buggy results (~20% failure rate) they weren't consistent like last time. Since PP7 added the follower feature into the newest version we just switched to that.

I'll try to add the info next time I'm there for you. I did not update anything since discovering the initial issue.

**Comment by greyshirtguy** [comment]
It does not have any re-try logic built in.  If your network is not perfect in delivering the packets - it can easily miss some tirggers.  I'm going to close this issue now as the feature was always "beta" and I think the new network link feature totally trumps this by one million percent!
